### ISSUE TITLE
Why not SM17?

### ISSUE THREAD

**Issue by linonetwo** [sunaiwen/supermemo2.js#3]
Seems latest algorithm is SM17

**Comment by sunaiwen** [comment]
Sorry, I haven’t followed this field for a long time.  🙁

**Comment by linonetwo** [comment]
如果你最近还关注知识管理的话，欢迎加入集智俱乐部注意力与知识管理群的微信群来一起讨论

**Comment by sunaiwen** [comment]
> 如果你最近还关注知识管理的话，欢迎加入集智俱乐部注意力与知识管理群的微信群来一起讨论

谢谢！我现在暂时不关注这一块了 。
